#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
import setuptools

with open('README') as f:
	long_description = f.read()

setup_params = dict(
	name='wolframalpha',
	use_hg_version=True,
	description="Wolfram|Alpha 2.0 API client",
	long_description = long_description,
	author="Jason R. Coombs",
	author_email="jaraco@jaraco.com",
	url="https://bitbucket.org/jaraco/wolframalpha",
	packages=setuptools.find_packages(),
	zip_safe=False,
	setup_requires=[
		'hgtools',
	],
)
if __name__ == '__main__':
	setuptools.setup(**setup_params)
